zuul:
  routes:
    foobar:
      path: /foobar/**
      url: http://localhost:8080/foo
    foobaz:
      path: /foobaz/**
      url: http://localhost:8080/bar
  retryable: false

ribbon:
  eureka:
    enabled: false